pipeline {
    agent any
    
    tools {
      terraform 'Terraform'
    }

    stages {

        stage('clean Workspace') {
            steps {
                cleanWs()
              }
        }

        stage('Checkout SCM') {
            steps {
              checkout scmGit(branches: [[name: '*/development']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/irfan-1117/aws-infra.git']])
            }
        }

        stage('Backend-s3') {
            steps {
                script {
                  withCredentials([usernameColonPassword(credentialsId: 'AWS-CRED', variable: 'AWS')]) {
                     sh "cd $WORKSPACE/backend-support"
                     sh "terraform init"
                  }
                }  
            }
        }
    }
}
