---
- name: Copy Public Key to Remote Host
  hosts: application-server
  become: true

  vars:
    remote_username: appuser
    public_key_path: .ssh/id_rsa.pub

  tasks:
    - name: Create .ssh directory
      file:
        path: /home/{{ remote_username }}/.ssh
        state: directory
        mode: "0700"

    - name: Copy public key to remote host
      authorized_key:
        user: "{{ remote_username }}"
        key: "{{ lookup('file', public_key_path) }}"
        state: present

