---
- name: Install Docker Compose
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Install dependencies
      become: true
      apt:
        name: ['python3-pip']
        state: present

    - name: Install Docker Compose
      become: true
      pip:
        name: docker-compose
        executable: pip3
        state: present
